// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_курсач_0_H
#define WINRT_курсач_0_H
WINRT_EXPORT namespace winrt::курсач
{
    struct IBlankPage;
    struct BlankPage;
}
namespace winrt::impl
{
    template <> struct category<winrt::курсач::IBlankPage>{ using type = interface_category; };
    template <> struct category<winrt::курсач::BlankPage>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::курсач::BlankPage> = L"курсач.BlankPage";
    template <> inline constexpr auto& name_v<winrt::курсач::IBlankPage> = L"курсач.IBlankPage";
    template <> inline constexpr guid guid_v<winrt::курсач::IBlankPage>{ 0x8F9C0F3B,0xE204,0x5483,{ 0x81,0x11,0x30,0x8E,0xF8,0x72,0xDA,0xA3 } }; // 8F9C0F3B-E204-5483-8111-308EF872DAA3
    template <> struct default_interface<winrt::курсач::BlankPage>{ using type = winrt::курсач::IBlankPage; };
    template <> struct abi<winrt::курсач::IBlankPage>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_курсач_IBlankPage
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::курсач::IBlankPage>
    {
        template <typename D> using type = consume_курсач_IBlankPage<D>;
    };
}
#endif
