// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_курсач_H
#define WINRT_курсач_H
#include "winrt/base.h"
static_assert(winrt::check_version(CPPWINRT_VERSION, "2.0.220531.1"), "Mismatched C++/WinRT headers.");
#define CPPWINRT_VERSION "2.0.220531.1"
#include "winrt/impl/Windows.UI.Composition.2.h"
#include "winrt/impl/Windows.UI.Xaml.2.h"
#include "winrt/impl/Windows.UI.Xaml.Controls.2.h"
#include "winrt/impl/курсач.2.h"
namespace winrt::impl
{
    template <typename D> auto consume_курсач_IBlankPage<D>::MyProperty() const
    {
        int32_t value{};
        check_hresult(WINRT_IMPL_SHIM(winrt::курсач::IBlankPage)->get_MyProperty(&value));
        return value;
    }
    template <typename D> auto consume_курсач_IBlankPage<D>::MyProperty(int32_t value) const
    {
        check_hresult(WINRT_IMPL_SHIM(winrt::курсач::IBlankPage)->put_MyProperty(value));
    }
    template <typename D>
    struct produce<D, winrt::курсач::IBlankPage> : produce_base<D, winrt::курсач::IBlankPage>
    {
        int32_t __stdcall get_MyProperty(int32_t* value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            *value = detach_from<int32_t>(this->shim().MyProperty());
            return 0;
        }
        catch (...) { return to_hresult(); }
        int32_t __stdcall put_MyProperty(int32_t value) noexcept final try
        {
            typename D::abi_guard guard(this->shim());
            this->shim().MyProperty(value);
            return 0;
        }
        catch (...) { return to_hresult(); }
    };
}
WINRT_EXPORT namespace winrt::курсач
{
    inline BlankPage::BlankPage() :
        BlankPage(impl::call_factory_cast<BlankPage(*)(winrt::Windows::Foundation::IActivationFactory const&), BlankPage>([](winrt::Windows::Foundation::IActivationFactory const& f) { return f.template ActivateInstance<BlankPage>(); }))
    {
    }
}
namespace std
{
#ifndef WINRT_LEAN_AND_MEAN
    template<> struct hash<winrt::курсач::IBlankPage> : winrt::impl::hash_base {};
    template<> struct hash<winrt::курсач::BlankPage> : winrt::impl::hash_base {};
#endif
#ifdef __cpp_lib_format
#endif
}
#endif
